// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vidvcmloyjyvtxledsfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZHZjbWxveWp5dnR4bGVkc2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NDIxNTYsImV4cCI6MjA3NTQxODE1Nn0.koFrd4fVb6j9b06US0I0zn7TIMZdtrqSKCYGfOgti1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});